import { Contract, RiskLevel } from './types';

export const contracts: Contract[] = [
  {
    id: 'c1',
    vendorName: 'CloudNova Hosting',
    contractName: 'Global Cloud Hosting MSA – EMEA',
    renewalDate: '2026-08-01',
    daysRemaining: 45,
    value: '$1.2M ARR',
    commercialRisk: RiskLevel.High,
    complianceRisk: RiskLevel.High,
    riskReason: '3-year auto-renew + 7% uplift + outdated DPA terms',
    term: '36 months',
    uplift: '7% annual',
    slaBreaches: 3,
    noticePeriod: '90 days',
    type: 'Auto-renew',
    description: 'Primary hosting infrastructure for EMEA region data processing.',
    region: 'EMEA'
  },
  {
    id: 'c2',
    vendorName: 'DataStream Analytics',
    contractName: 'Enterprise Analytics License',
    renewalDate: '2026-08-15',
    daysRemaining: 59,
    value: '$450K / year',
    commercialRisk: RiskLevel.Medium,
    complianceRisk: RiskLevel.Low,
    riskReason: 'Consumption exceeded commitment by 20%',
    term: '12 months',
    uplift: '3%',
    slaBreaches: 0,
    noticePeriod: '60 days',
    type: 'Auto-renew',
    description: 'Data visualization and processing suite.',
    region: 'NA'
  },
  {
    id: 'c3',
    vendorName: 'SecureNet Ops',
    contractName: 'Security Operations Center (SOC) Retainer',
    renewalDate: '2026-09-01',
    daysRemaining: 76,
    value: '$2.1M ARR',
    commercialRisk: RiskLevel.High,
    complianceRisk: RiskLevel.Medium,
    riskReason: 'Auto-renewal lock-in; 10% price hike triggered if no notice',
    term: '24 months',
    uplift: '10%',
    slaBreaches: 5,
    noticePeriod: '120 days',
    type: 'Auto-renew',
    description: 'Managed security services and threat detection.',
    region: 'NA'
  },
  {
    id: 'c4',
    vendorName: 'HR Connect',
    contractName: 'Global HRIS Platform',
    renewalDate: '2026-07-20',
    daysRemaining: 33,
    value: '$800K / year',
    commercialRisk: RiskLevel.Low,
    complianceRisk: RiskLevel.High,
    riskReason: 'GDPR clauses missing for new EU territories',
    term: '36 months',
    uplift: 'CPI',
    slaBreaches: 1,
    noticePeriod: '30 days',
    type: 'Auto-renew',
    description: 'Human resources information system.',
    region: 'EMEA'
  },
  {
    id: 'c5',
    vendorName: 'LogiTech Fleet',
    contractName: 'Logistics Fleet Management',
    renewalDate: '2026-10-05',
    daysRemaining: 110,
    value: '$3.5M ARR',
    commercialRisk: RiskLevel.Medium,
    complianceRisk: RiskLevel.Medium,
    riskReason: 'Volume discounts expiring',
    term: '48 months',
    uplift: '2%',
    slaBreaches: 2,
    noticePeriod: '90 days',
    type: 'Fixed Term',
    description: 'Fleet tracking and logistics optimization.',
    region: 'NA'
  },
  {
    id: 'c6',
    vendorName: 'QuickShip APAC',
    contractName: 'Regional Distribution Logistics',
    renewalDate: '2026-06-25',
    daysRemaining: 12,
    value: '$950K / year',
    commercialRisk: RiskLevel.High,
    complianceRisk: RiskLevel.Low,
    riskReason: 'Urgent: Auto-renews in 10 days with 15% uplift',
    term: '12 months',
    uplift: '15%',
    slaBreaches: 4,
    noticePeriod: '30 days',
    type: 'Auto-renew',
    description: 'Last-mile delivery services for Southeast Asia.',
    region: 'APAC'
  },
  {
    id: 'c7',
    vendorName: 'DevCloud Studio',
    contractName: 'Developer Tools Suite',
    renewalDate: '2026-06-29',
    daysRemaining: 16,
    value: '$320K / year',
    commercialRisk: RiskLevel.Low,
    complianceRisk: RiskLevel.High,
    riskReason: 'DPA non-compliant with new AI policy',
    term: '12 months',
    uplift: '5%',
    slaBreaches: 0,
    noticePeriod: '30 days',
    type: 'Auto-renew',
    description: 'Integrated development environment and CI/CD tools.',
    region: 'EMEA'
  },
  {
    id: 'c8',
    vendorName: 'MarketingPro Suite',
    contractName: 'Global Marketing Automation',
    renewalDate: '2026-07-15',
    daysRemaining: 28,
    value: '$1.1M / year',
    commercialRisk: RiskLevel.High,
    complianceRisk: RiskLevel.Low,
    riskReason: 'Significant under-utilization of seats; 20% potential saving',
    term: '12 months',
    uplift: '8%',
    slaBreaches: 0,
    noticePeriod: '30 days',
    type: 'Auto-renew',
    description: 'Marketing automation and email campaign tools.',
    region: 'NA'
  },
  {
    id: 'c9',
    vendorName: 'Legacy Storage Corp',
    contractName: 'Archival Data Storage',
    renewalDate: '2026-08-10',
    daysRemaining: 54,
    value: '$200K / year',
    commercialRisk: RiskLevel.Low,
    complianceRisk: RiskLevel.High,
    riskReason: 'DPA missing for new California regulations',
    term: '24 months',
    uplift: '2%',
    slaBreaches: 0,
    noticePeriod: '60 days',
    type: 'Auto-renew',
    description: 'Cold storage for historical records.',
    region: 'NA'
  }
];